name: Problem
description: Create a issue
labels: [problem]
body:
    - type: markdown
      attributes:
          value: |
              **IMPORTANT:** Before submitting:             
              - check whether your [device](https://www.zigbee2mqtt.io/supported-devices/) is supported 

    - type: textarea
      id: what_problem
      attributes:
          label: what does not work?
      validations:
          required: true
    
    - type: input
      id: adapter_version
      attributes:
          label: Adapter version
          description: Can be found in the Admin GUI
          placeholder: '1.10.3'
      validations:
          required: true
    - type: input
      id: coordinator_type
      attributes:
          label: Coordinator 
          description: 
          placeholder: Electrolama zig-a-zig-ah! (zzh!), Slaeshs CC2652RB stick, SONOFF Zigbee 3.0 USB Dongle Plus....
      validations:
          required: true
    - type: input
      id: coordinator_fwversion
      attributes:
          label: Coordinator firmware version
          description: Can be found in the Adapter settings
          placeholder: '20230921'
      validations:
          required: true
      - type: input
      id: setup
      attributes:
          label: Setup
          description: How do you run the adapter 
          placeholder: Add-on on Intel NUC, Docker container, RaspberryPi...
      validations:
          required: true
    - type: textarea
      id: log
      attributes:
          label: Debug log
          description: first 50 rows after starting adapter
          placeholder: Click here and drag the file into it or click on "Attach files by.." below
      validations:
          required: false
          
